### ISSUE TITLE
CUDA Out of Memory Error on trying to train on local machine

### ISSUE THREAD

**Issue by sampreets3** [sea-bass/detectron2-tutorial#1]
Hi @sea-bass, thanks for the awesome tutorial on MRCNN with Detectron2. I was trying out your example Jupyter Notebook on my local machine for training. I have a small [NVIDIA GeForce 940M](https://www.notebookcheck.biz/NVIDIA-GeForce-940M.142800.0.html), which I am using for training. I have all the libraries installed correctly, and I am running the file `detectron2_tutorial.ipynb'. The pretrained notebook works fine, however I am interested in training my own model for custom class inference. 

### Description of the Problem:
In the file `detectron2_tutorial.ipynb` in Cell 5, where we call the training on the dataset, I get the following error:
```sh
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 1.96 GiB total capacity; 1.16 GiB already allocated; 8.94 MiB free; 1.20 GiB reserved in total by PyTorch)
[06/16 13:52:58 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
[06/16 13:52:58 d2.utils.events]:  iter: 1  total_loss: 3.513  loss_cls: 1.88  loss_box_reg: 0.9322  loss_mask: 0.6928  loss_rpn_cls: 0.001989  loss_rpn_loc: 0.00643  data_time: 0.4304  lr: 1e-06  max_mem: 1186M
```
It seems that I am running out of memory just after one iteration. I would like to know if there is a minimum amount of GPU memory that I need to have. How can I free up the memory during training so that I can train for at least 100 iterations? 

Also, do you think running this example on Colab would provide better results?

### System Description:
Key | Value
----- | ------
OS | Ubuntu Focal Fossa 20.04 LTS
PyTorch | Installed (conda), v1.8.1
torchvision | Installed (conda), v1.8.1
detectron2 | installed, v0.4
NVIDIA GPU | Yes, GeForce 940M
GPU Memory | 2GB
CUDA Version | v11.2

Thanks a lot for your help!

**Comment by sea-bass** [comment]
2 GB is not a whole lot of GPU memory for training object detectors, but there are ways to try keep memory usage down if you want to try.

First off, you should minimize the training batch size itself. I believe this tutorial already has memory usage in mind so the batch size is all the way down at 1:

```
cfg.SOLVER.IMS_PER_BATCH = 1 
```

Additionally, there are ways to  ensure a minimum image size for training, using the property corresponding to "Size of the smallest side of the image during training". This is done as follows, for instance, where 800 pixels is the default.

```
cfg.INPUT.MIN_SIZE_TRAIN = 300
```

More generally,  you should refer to the Detectron2 configuration reference at https://detectron2.readthedocs.io/en/latest/modules/config.html#config-references

On the same note of image size, my tutorial defined data augmentations which resize the image to a bunch of random sizes:

```
augs = [transforms.ResizeShortestEdge(
                    [640, 672, 704, 736, 768, 800],
                     max_size=1333, sample_style="choice")
```

So notice that you could also bring that list of values, as well as the `max_size` parameter, down to a smaller number. You'll be training on smaller images which will obviously affect performance on full-size images... but if you can't train on a batch size of 1 for the full-size image, you'll be close to running into memory issues doing inference at runtime with the full-sized images as well.

Hope this helps.
